baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Sammy Shear"
googleAnalytics = "G-VFQTT95X39"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'catppuccin-latte'
    tabWidth = 4
